routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// route product
Route::name('product.')->group(function () {
    Route::get('/product', 'ProductController@index')->name('index');
    Route::post('/product', 'ProductController@store')->name('store');
    Route::put('/product/update/{product}', 'ProductController@update')->name('update');
    Route::delete('/product/delete/{transaction}', 'ProductController@destroy')->name('delete');
    Route::resource('products', 'ProductController');
});

// route categories
Route::name('category.')->group(function () {
    Route::get('/category', 'CategoryController@index')->name('index');
    Route::post('/category', 'CategoryController@store')->name('store');
    Route::put('/category/update/{category}', 'CategoryController@update')->name('update');
    Route::delete('/category/delete/{category}', 'CategoryController@destroy')->name('delete');
    Route::resource('categories', 'CategoryController');
});

resources/views/home.blade.php
@extends('layouts.template')

@section('title', 'TOKOKU')

@section('content')
<div class="container">
    <!-- <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div> -->
    <div class="row justify-content-center text-center mt-5">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <img src="{{asset('assets/img/product.png')}}" class="img-fluid" width="320px">
                    <a href="{{route('product.products.index')}}" class="btn btn-primary">Go to Product</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body text-center">
                    <img src="{{asset('assets/img/category.png')}}" class="img-fluid" width="300px">
                    <a href="{{route('category.categories.index')}}" class="btn btn-primary">Go to Category</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/landing.blade.php
@extends('layouts.template')

@section('title')
    Product | Pemweblan
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <img src="{{asset('assets/img/landing.png')}}" class="img-fluid" width="320px">
        </div>
    </div>
</div>
@endsection