routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// route product
Route::name('product.')->group(function () {
    Route::get('/product', 'ProductController@index')->name('index');
    Route::post('/product', 'ProductController@store')->name('store');
    Route::put('/product/update/{product}', 'ProductController@update')->name('update');
    Route::delete('/product/delete/{transaction}', 'ProductController@destroy')->name('delete');
    Route::resource('products', 'ProductController');
});

// route categories
Route::name('category.')->group(function () {
    Route::get('/category', 'CategoryController@index')->name('index');
    Route::post('/category', 'CategoryController@store')->name('store');
    Route::put('/category/update/{category}', 'CategoryController@update')->name('update');
    Route::delete('/category/delete/{category}', 'CategoryController@destroy')->name('delete');
    Route::resource('categories', 'CategoryController');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    protected $table = 'categories';
    protected $fillable = ['name'];

    public function products()
    {
        return $this->hasMany('App\Models\Product');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\StoreCategory;
use App\Http\Requests\UpdateCategory;
use App\Models\Product;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $categories = Category::all();
        return view('categories.category', ['category' => $categories]);
    }

    public function create()
    {
        //
    }

    public function store(StoreCategory $request)
    {
        $data = $request->only('name');

        Category::create($data);

        return redirect()->route('category.categories.index')->with('success', 'Category created successfully.');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(UpdateCategory $request, Category $category)
    {
        $data = $request->only('name');

        $category->update($data);

        return redirect()->route('category.categories.index')->with('success', 'Category updated successfully');
    }

    public function destroy(Category $category)
    {
        if (Gate::denies('delete-category')) {
            return redirect()->back()->with('failed', "Admin Can't Delete Category");
        }
        $product = Product::where('categories_id', $category->id)->get();
        foreach ($product as $pr) {
            $pr->delete();
        }
        $category->delete();

        return redirect()->route('category.categories.index')->with('success', 'Category deleted successfully');
    }
}

resources/views/categories/category.blade.php
@extends('layouts.template')

@section('title', 'Product Categories')

@section('content')
<section class="product">
  <div class="section-body">
    <div class="row">
      <div class="col-md-12 col-lg-12">
        <div class="card">
          <div class="card-header">
            <h1>Data Kategori Produk</h1>
          </div>
          <div class="card-body">
            @if (session('success'))
            <div class="alert alert-success ml-auto">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              {{ session('success') }}
            </div>
            @elseif (session('failed'))
            <div class="alert alert-warning ml-auto">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              {{ session('failed') }}
            </div>
            @endif
            <div class="table-responsive">
              <button type="button" class="btn btn-primary mb-4" data-toggle="modal" data-target="#addModalKategori">
                Tambah Kategori
              </button>
              <table id="datatables" class="table table-hover table-striped table-bordered ">
                <thead>
                  <tr>
                    <th scope="col" class="text-center">No</th>
                    <th scope="col" class="text-center">Nama Kategori</th>
                    <th scope="col" class="text-center">Aksi</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($category as $index => $cat)
                  <tr>
                    <td class="text-center">{{ $index+1 }}</td>
                    <td class="text-center">{{ $cat->name }}</td>
                    <td class="text-center">
                      <div class="btn-action d-inline-flex">
                        <button class="btn btn-sm btn-success mx-2" title="edit" data-id="{{ $cat->id }}" data-name="{{ $cat->name }}" data-toggle="modal" data-target="#editModalKategori">
                          <i class="fas fa-edit"></i>
                        </button>
                        @can('delete-category')
                        <button class="btn btn-sm btn-danger mx-2" title="delete" data-id="{{ $cat->id }}" data-toggle="modal" data-target="#deleteModalKategori">
                          <i class="fas fa-trash"></i>
                        </button>
                        @endcan
                      </div>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Modal Add Data -->
<div class="modal fade" id="addModalKategori" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addModalLabel">Tambah Data Kategori</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" action="{{ route('category.categories.store') }}" enctype="multipart/form-data">
        @csrf
        <div class="modal-body">
          <div class="form-group">
            <label>Nama Kategori</label>
            <input type="text" class="form-control" name="name" id="name" placeholder="Nama Kategori">
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Tambah Kategori</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Edit Data -->
<div class="modal fade" id="editModalKategori" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Kategori</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form id="edit_modal" method="POST" action="">
        {{csrf_field()}}
        {{method_field('put')}}

        <div class="modal-body">
          <input type="hidden" name="id" id="id" value="">
          <div class="form-group">
            <label>Nama Kategori</label>
            <input type="text" class="form-control" name="name" id="name" value="">
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button0" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Delete Data -->
<div class="modal fade" id="deleteModalKategori" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Hapus Kategori</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form id="delete_modal" method="POST" action="">
        {{ csrf_field() }}
        {{ method_field('delete') }}

        <div class="modal-body">
          <input type="hidden" name="id" id="id" value="">
          <p>Apakah anda yakin akan menghapus data ini?</p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Tidak</button>
          <button type="submit" class="btn btn-primary">Ya, hapus</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script>
  $('#editModalKategori').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var name = button.data('name')
    var modal = $(this)

    let url = `{{ route('category.categories.update', '') }}/${id}`;
    $('#edit_modal').attr('action', url);

    modal.find('.modal-body #id').val(id);
    modal.find('.modal-body #name').val(name);
  })

  $('#deleteModalKategori').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('category.categories.destroy', '') }}/${id}`;
    $('#delete_modal').attr('action', url);
    modal.find('.modal-body #id').val(id);
  })
</script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#datatables').DataTable();
  });
</script>
@endsection